# @package _global_

env:
  name: SafetyCarButton1-v0

  replay_mem: 1e6

  eps_steps: 100000
  eps_window: 10
  learn_steps: 1e6
  eval_interval: 1e4
  clip_threshold: 0.55

expert:
  demos: 1
  subsample_freq: 1

eval:
  eps: 100
  n_envs: 25

agent:
  name: sac

log_interval: 500  # Log every this many steps
num_actor_updates: 1

train:
  use_target: true
  soft_update: true
  batch: 256

q_net:
  _target_: agent.sac_models.DoubleQCritic